services:
  mongo:
    container_name: ddev-${DDEV_SITENAME}-mongo
    image: mongo:6.0
    volumes:
      - type: "volume"
        source: mongo
        target: "/data/db"
        volume:
          nocopy: true
    restart: "no"
    expose:
      - "27017"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
    environment:
      - MONGO_INITDB_ROOT_USERNAME=db
      - MONGO_INITDB_ROOT_PASSWORD=db
      - MONGO_INITDB_DATABASE=db

  mongo-express:
    container_name: ddev-${DDEV_SITENAME}-mongo-express
    image: mongo-express:latest
    restart: "no"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: ${DDEV_APPROOT}
      com.ddev.platform: ddev

    links:
      - mongo:mongo
    expose:
      - "8081"
    environment:
      VIRTUAL_HOST: $DDEV_HOSTNAME
      ME_CONFIG_MONGODB_ADMINUSERNAME: db
      ME_CONFIG_MONGODB_ADMINPASSWORD: db
      ME_CONFIG_MONGODB_URL: mongodb://db:db@mongo:27017/
      HTTPS_EXPOSE: "8081:8081"

  web:
    links:
      - mongo:mongo

volumes:
  mongo:
